language: node_js
sudo: false

node_js:
  - 8
  - 9

script:
  - npm test
  - pushd packages/javascript && npm test && popd
  - pushd packages/react && npm test && popd
  - pushd packages/flow && npm test && popd
